{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.3.jar",
          "url": "spring-test-6.2.3.jar",
          "size": 1021026,
          "sha512": "247056651544960eacd4e92debf1612da5c7a51220e1cd64449f083cc04c38383898e6334f5213c21336a35631aa2996b070158c528e0d29838e628cd4105456",
          "sha256": "349eaa7d8d496a3b68490ccc722f04cbd711ce4308300c5922a13bb207469bc6",
          "sha1": "92fbfd7a88dd007f4c669d8a317227d2757a4d2a",
          "md5": "26aa28f8b5b4ecbd45eeeddace88b483"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.3.jar",
          "url": "spring-test-6.2.3.jar",
          "size": 1021026,
          "sha512": "247056651544960eacd4e92debf1612da5c7a51220e1cd64449f083cc04c38383898e6334f5213c21336a35631aa2996b070158c528e0d29838e628cd4105456",
          "sha256": "349eaa7d8d496a3b68490ccc722f04cbd711ce4308300c5922a13bb207469bc6",
          "sha1": "92fbfd7a88dd007f4c669d8a317227d2757a4d2a",
          "md5": "26aa28f8b5b4ecbd45eeeddace88b483"
        }
      ]
    }
  ]
}
